In [1]:
import pickle 
import numpy as np

In [3]:
ohe_sex=pickle.load(open('ohe_sex.pkl','rb'))

In [6]:
ohe_embarked=pickle.load(open('ohe_embarked.pkl','rb'))


In [7]:
clf=pickle.load(open('clf.pkl','rb'))

#### asume user provide input Pclass/gender/age/SibSp/Parch/Fare/Embarked

In [10]:
test_input=np.array([2,'male',31.0,0,0,10.5,'S'],dtype=object).reshape(1,7)

In [11]:
test_input


array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [13]:
test_input_sex=ohe_sex.transform(test_input[:,1].reshape(1,1))

C:\Users\tyagi\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [14]:
test_input_sex

array([[0., 1.]])

In [17]:
test_input_embarked=ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [18]:
test_input_embarked

array([[0., 0., 1.]])

In [20]:
test_input_age=test_input[:,2].reshape(1,1)


In [21]:
test_input_transformed=np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [22]:
test_input_transformed.shape

(1, 10)

In [23]:
clf.predict(test_input_transformed)

array([1])